### ISSUE TITLE
Two Genie openers

### ISSUE THREAD

**Issue by bigjayman1** [iAnatoly/homebridge-aladdin-connect-garage-door#18]
I get this error when I use the plugin?  Also, what info do you use if you have 2 separate garage doors at your house?
This plugin generated a warning from the characteristic 'Target Door State': characteristic was supplied illegal value: number 4 exceeded maximum of 1.  

Thank you, love to get this corrected.

**Comment by caseyrichards** [comment]
Same here. I can only get one overhead door unit to work at a time. As soon as I try to add a second overhead door unit the function breaks on both. Have tried assigning all different Device IDs like it says but no luck. Please help as I would really love to be able to use both garage doors through HomeKit.

**Comment by apexad** [comment]
In thinking about this further it will likely require a re-write of the homebridge plugin and/or the corresponding API library https://github.com/apexad/node-aladdin-connect-garage-door to grab the status for both doors at the same time and maintain only a single connection. This may include auto-discovery of devices/garage doors rather than having to specify them.

I have limited time for homebridge plugins right now so I don't have ETA as to when I would be able to do this re-write.

**Comment by caseyrichards** [comment]
Correct two overhead door units each with their own Genie hub. So I tried placing Device 0, Door 1 and Device 1, Door 1 with staggered polling times. Didn't seem to change anything. Like I said they do work if I only install one plugin at a time but as soon as I install the second then they both break. So I'm not sure it's allowing grabbing two different devices. When you can let us know. Thanks!

**Comment by apexad** [comment]
@bigjayman1 version 1.0.3 should fix the `warning from the characteristic 'Target Door State': characteristic was supplied illegal value: number 4 exceeded maximum of 1.`

**Comment by caseyrichards** [comment]
Thanks! This new version is actually working a lot better for me and seems to also solve the two device issue. The only thing now is that a lot of times the Homekit icons will just spin while saying either Opening or Closing. The only way to fix it is click on each one which then seems to update to the true status and go on to work fine after that. Any ideas why this happens now?

**Comment by apexad** [comment]
Hmm, this means current door state and target door state are getting out of sync. Will take a look

**Comment by caseyrichards** [comment]
Any updates on a fix for this?

**Comment by apexad** [comment]
As I mentioned previously, there is no 'fix' to do.  This requires a complete re-write of the plugin/libray to handle multiple garage doors at the same time.  I have looked into it and done some preliminary work but no ETA at this time.  Busy with life at the moment.  Hopefully soon though.

**Comment by apexad** [comment]
Just a heads up, I was able to spend a little bit of time today and did get open/close working again in my 'rewrite' of the main library.  Next up is a 'Get Doors' function which will return the doors you have on your account so that this plugin can consume that and you will simply have to provide username/password.

Of course, after that I have to rewrite get status function as well so it too will return status for all doors, not just 1.  With the long weekend coming up, I hope I can do this then.

**Comment by apexad** [comment]
Progress on this can be tracked here:
https://github.com/apexad/node-aladdin-connect-garage-door/milestone/1
